### ISSUE TITLE
"Something went wrong"

### ISSUE THREAD

**Issue by anseltaft** [umami-software/umami#2125] opened 2023-07-14 00:09 UTC
### Describe the Bug

Since the last update Umami's been chugging along in a docker instance, I check it almost every day, then today I see this:

"Something went wrong.

[@formatjs/intl] An `id` must be provided to format a message. You can either: 1. Configure your build toolchain with [babel-plugin-formatjs](https://formatjs.io/docs/tooling/babel-plugin) or [@formatjs/ts-transformer](https://formatjs.io/docs/tooling/ts-transformer) OR 2. Configure your `eslint` config to include [eslint-plugin-formatjs](https://formatjs.io/docs/tooling/linter#enforce-id) to autofix this issue
Error: [@formatjs/intl] An `id` must be provided to format a message. You can either:
1. Configure your build toolchain with [babel-plugin-formatjs](https://formatjs.io/docs/tooling/babel-plugin)
or [@formatjs/ts-transformer](https://formatjs.io/docs/tooling/ts-transformer) OR
2. Configure your `eslint` config to include [eslint-plugin-formatjs](https://formatjs.io/docs/tooling/linter#enforce-id)
to autofix this issue

    at r (https://mysubdomain.com/_next/static/chunks/pages/_app-0e67ddf2180faf84.js:1:150)
    at m (https://mysubdomain.com/_next/static/chunks/pages/_app-0e67ddf2180faf84.js:6:546061)
    at Y (https://mysubdomain.com/_next/static/chunks/pages/_app-0e67ddf2180faf84.js:6:555082)
    at R (https://mysubdomain.com/_next/static/chunks/pages/dashboard-2c62d3766cf4e359.js:1:4926)
    at ab (https://mysubdomain.com/_next/static/chunks/framework-2c79e2a64abdb08b.js:9:60915)
    at ud (https://mysubdomain.com/_next/static/chunks/framework-2c79e2a64abdb08b.js:9:72801)
    at i (https://mysubdomain.com/_next/static/chunks/framework-2c79e2a64abdb08b.js:9:120370)
    at oO (https://mysubdomain.com/_next/static/chunks/framework-2c79e2a64abdb08b.js:9:99112)
    at https://mysubdomain.com/_next/static/chunks/framework-2c79e2a64abdb08b.js:9:98979
    at oF (https://mysubdomain.com/_next/static/chunks/framework-2c79e2a64abdb08b.js:9:98986)"

I'm not sure which of the two suggestions looks easier to fix the problem (any suggestions?) but my real concern is how things like this happen? I didn't do anything other than update the OS-level software on the system. Is there some maintenance I need to perform on the docker instance from time to time?

Update: It's been super flakey. Part of the time the dashboard comes up correctly and part of the time I get the error above.

Cheers

### Database

PostgreSQL

### How are you deploying your application? (if relevant)

Docker (Compose)

**Comment by franciscao633** [comment] 2023-07-14 00:18
Looks like a duplicate of #2113 . Pull the latest version, install, and build. I will close this, but feel free to comment in the other issue.

**Closed by franciscao633** 2023-07-14 00:18 UTC

**Comment by anseltaft** [comment] 2023-07-14 00:32
I'm sorry - I looked through the last few issues but didn't check that one. It would seem I did open a duplicate issue and updating seems to have fixed it.
