### ISSUE TITLE
Auto-filled credentials not working in Firefox

### ISSUE THREAD

**Issue by nordowl** [umami-software/umami#2814] opened 2024-06-25 13:42 UTC
### Describe the Bug

I'm using Umami cloud and when I want to log in, Firefox automatically fills in the email and password fields, because I have my passwords stored in Firefox. However it seems like the values are not stored in a state, because when I try to log in I get an error saying the fields are supposedly empty.
I have to manually type and delete a character in either fields for it to recognize the values.

![Screenshot_2](https://github.com/umami-software/umami/assets/71926058/7f98ad1b-02d3-4933-ae2f-a52cbe597d1e)

### Database

Umami Cloud

### Which Umami version are you using? (if relevant)

Cloud

### Which browser are you using? (if relevant)

Firefox

**Comment by franciscao633** [comment] 2024-07-01 22:33
Duplicate of #2449, but yea need to get around to this, its a really old bug.

**Closed by franciscao633** 2024-07-01 22:33 UTC
