### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'toString')

### ISSUE THREAD

**Issue by axelsegebrecht** [umami-software/umami#2817] opened 2024-06-27 07:30 UTC
### Describe the Bug

When browsing to the Event Data part of any website (event-data), the page displays the following error instead: "TypeError: Cannot read properties of null (reading 'toString')"

### Database

MySQL

### Relevant log output

```shell
TypeError: Cannot read properties of null (reading 'toString')
    at t.Z (https://<host>.pikapod.net/_next/static/chunks/4994-a5f59a12a07941bf.js:1:8033)
    at rE (https://<host>.pikapod.net/_next/static/chunks/fd9d1056-32e91c42f6a1484e.js:1:40344)
    at iZ (https://<host>.pikapod.net/_next/static/chunks/fd9d1056-32e91c42f6a1484e.js:1:117029)
    at ia (https://<host>.pikapod.net/_next/static/chunks/fd9d1056-32e91c42f6a1484e.js:1:95165)
    at https://<host>.pikapod.net/_next/static/chunks/fd9d1056-32e91c42f6a1484e.js:1:94987
    at il (https://<host>.pikapod.net/_next/static/chunks/fd9d1056-32e91c42f6a1484e.js:1:94994)
    at oJ (https://<host>.pikapod.net/_next/static/chunks/fd9d1056-32e91c42f6a1484e.js:1:92350)
    at nb (https://<host>.pikapod.net/_next/static/chunks/fd9d1056-32e91c42f6a1484e.js:1:26836)
    at nw (https://<host>.pikapod.net/_next/static/chunks/fd9d1056-32e91c42f6a1484e.js:1:27574)
    at https://<host>.pikapod.net/_next/static/chunks/fd9d1056-32e91c42f6a1484e.js:1:28608
```

### Which Umami version are you using? (if relevant)

v2.12.0

### Which browser are you using? (if relevant)

Vivaldi 6.8.3381.44 (Stable channel) (64-bit) (Windows 10)

### How are you deploying your application? (if relevant)

Pikapods / Docker

**Comment by m3nu** [comment] 2024-06-27 12:12
Duplicate of #2798?

**Closed** 2024-06-27 13:41 UTC
