### ISSUE TITLE
Default date in empty

### ISSUE THREAD

**Issue by Jaarson** [umami-software/umami#2759] opened 2024-05-27 08:35 UTC
### Describe the Bug

After updating my self-hosted Umami, the default date is always empty. Now every time, I need to manually select an option from the dropdown.

See:
<img width="1289" alt="SCR-20240527-jntf-2" src="https://github.com/umami-software/umami/assets/16690523/de1804a5-00e1-407d-ad94-9e4ef383478f">

### Database

PostgreSQL

### Relevant log output

```shell
yarn run v1.22.19
$ npm-run-all check-db update-tracker start-server
$ node scripts/check-db.js
✓ DATABASE_URL is defined.
✓ Database connection successful.
✓ Database version check successful.
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "umami", schema "public" at "db:5432"

6 migrations found in prisma/migrations

No pending migrations to apply.

✓ Database is up to date.
$ node scripts/update-tracker.js
$ node server.js
   ▲ Next.js 14.1.4
   - Local:        http://localhost:3000
   - Network:      http://0.0.0.0:3000

 ✓ Ready in 344ms
PrismaClientValidationError: 
Invalid `prisma.websiteEvent.create()` invocation:

{
  data: {
    ...
    eventName: null,
+   websiteId: String
  }
}

Argument `websiteId` is missing.
    at Tn (/app/node_modules/@prisma/client/runtime/library.js:115:5888)
    at In.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:122:6510)
    at In.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:122:6188)
    at In.request (/app/node_modules/@prisma/client/runtime/library.js:122:5896)
    at async l (/app/node_modules/@prisma/client/runtime/library.js:127:11167)
    at async h (/app/.next/server/pages/api/send.js:1:3054)
    at async K (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16545)
    at async U.render (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16981)
    at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:554:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/next/dist/server/next-server.js:266:37) {
  clientVersion: '5.12.1'
}
PrismaClientValidationError: 
Invalid `prisma.websiteEvent.create()` invocation:

{
  data: {
    id: "7495909f-c4d5-483b-9cbb-c2b4d7c7425a",
    sessionId: undefined,
    visitId: "5cda8e2c-f4fa-5ee6-8fba-41beb4874dd9",
    urlPath: "/releases",
    urlQuery: undefined,
    referrerPath: "/",
    referrerQuery: undefined,
    referrerDomain: "",
    pageTitle: "Kerlig™ - In-context AI writing assistant for macOS",
    eventType: 1,
    eventName: null,
+   websiteId: String
  }
}

...

Raw query failed. Code: `2201X`. Message: `ERROR: OFFSET must not be negative`
    at In.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:122:6854)
    at In.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:122:6188)
    at In.request (/app/node_modules/@prisma/client/runtime/library.js:122:5896)
    at async l (/app/node_modules/@prisma/client/runtime/library.js:127:11167)
    at async m (/app/.next/server/pages/api/websites/[websiteId]/metrics.js:1:3217)
    at async K (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16545)
    at async U.render (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16981)
    at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:554:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/next/dist/server/next-server.js:266:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/next/dist/server/base-server.js:791:17) {
  code: 'P2010',
  clientVersion: '5.12.1',
  meta: { code: '2201X', message: 'ERROR: OFFSET must not be negative' }
}
PrismaClientKnownRequestError: 
Invalid `prisma.$queryRawUnsafe()` invocation:
```

### Which Umami version are you using? (if relevant)

2.11.3

### How are you deploying your application? (if relevant)

Docker

**Comment by franciscao633** [comment] 2024-05-28 15:23
Error logs looks like an exact duplicate of #2752. This will get resolved next release.

**Closed by franciscao633** 2024-05-28 15:23 UTC
