### ISSUE TITLE
BUG: Combined page views does not merge query params

### ISSUE THREAD

**Issue by tairosonloa** [umami-software/umami#1790] opened 2023-02-17 13:52 UTC
Hi mikecao (and usual contributors)!

I think this is a bug, so I wanted to report it. Please, inform me if this is the intended behavior.

## Description of the problem

Pages views to a same page are not being merged when using the "combined" filter in the dashboad.

## Expected behavior

I expect pages visits to a same page (but with different query params) to be merged into the page URL when using the "combined" filter in the page views analytics.

### Example

Let's suppose I have an article under `/blog/my-article`. I receive visits to it from searchers, but also marketing campaigns, and also people share it on social media. So at the end, different people end visiting:

- `/blog/my-article` (eg: from Google)
- `/blog/my-article?utm_source=newsletter` (eg: from marketing)
- `/blog/my-article?fbclid=abcd` (eg: people sharing it on facebook)

Let's say I have the following visits:

- `/blog/my-article`: 10
- `/blog/my-article?utm_source=newsletter`: 5
- `/blog/my-article?fbclid=abcd`: 5

The above it is what I see (and expect to see) when I check my visits with the raw filter. However, when I select the "combined" filter, I expect to see:

- `/blog/my-article`: 20 

But still I'm seeing them separately.

### Screenshot
![Captura de pantalla 2023-02-17 145131](https://user-images.githubusercontent.com/14878189/219673168-627c26ca-9b29-4125-a806-40fc7160af5a.png)

**Comment by d19dotca** [comment] 2023-02-21 04:52
I've noticed this too. Newer user to Umami so figured I was just expecting something incorrectly, but I think you have the same expectation I do. I can confirm it isn't working how we'd expect it to either in my install.

**Comment by franciscao633** [comment] 2023-03-06 23:36
duplicate of #1730

**Closed** 2023-03-06 23:37 UTC
Labels: bug, fixed in dev
