### ISSUE TITLE
Shareable Link Make Me Login to Dashboard

### ISSUE THREAD

**Issue by mdestafadilah** [umami-software/umami#1748] opened 2023-01-18 08:04 UTC
![18-01-2023 15-03-25](https://user-images.githubusercontent.com/5575882/213116406-3216bca5-30d1-4a95-bd8d-eabbbccb53af.png)

**Comment by briancao** [comment] 2023-01-19 01:56
Duplicate of https://github.com/umami-software/umami/issues/1720.  Have it fixed.  We'll be preparing a security release this week.

**Comment by briancao** [comment] 2023-01-19 06:51
Closing as dupe.

**Closed by briancao** 2023-01-19 06:51 UTC
Labels: duplicate
