### ISSUE TITLE
Problem after V2 migration

### ISSUE THREAD

**Issue by AugustinHavas** [umami-software/umami#2032] opened 2023-05-09 09:48 UTC
### Describe the Bug

Hi,
After migrating to V2, the docker container work properly.
But after approximatively 1 day, the app show only menus with nothing inside and when i try to loggin, no error shown but the loader rotates without stopping.

I don't have this problem with V1. Is there something change between V1 and V2 for databases ?
Any way to have more logs ?

Have a good day

### Database

MySQL

### Which browser are you using? (if relevant)

all

### How are you deploying your application? (if relevant)

docker

**Comment by tim-hub** [comment] 2023-05-10 22:07
I got a similar issue on Posrgres.



```

✓ Database is up to date.
$ node scripts/update-tracker.js
$ node server.js
Listening on port 3000 url: http://zkkff:3000
error Command failed with signal "SIGSEGV".

```

deployed in k8s, but the app itself keep failing then restarting,

**Comment by larsparendt** [comment] 2023-05-11 08:03
Same here: 
```
error Command failed with signal "SIGSEGV".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "start-server" exited with 1.
```
Running in container on ARM CPU + Postgres.

**Comment by franciscao633** [comment] 2023-05-11 16:03
We upgraded to prisma 4.13, which is causing issues. Looks like a duplicate of #1865. We will need to review before downgrading back to 4.9. Will close this and mark as duplicate.

**Closed by franciscao633** 2023-05-11 16:03 UTC
