### ISSUE TITLE
realtime logs all session show same color

### ISSUE THREAD

**Issue by lyragosa** [umami-software/umami#1544] opened 2022-09-30 04:08 UTC
before 1.37 the realtime log show different color for each session
bug after upgrade to version 1.38, the show same color. so cause hard to view

![image](https://user-images.githubusercontent.com/2680509/193187808-c8157857-f440-4c1c-a49e-760a7df8fbb7.png)

**Comment by mikecao** [comment] 2022-09-30 17:57
Duplicate of #1496

**Closed by mikecao** 2022-09-30 17:57 UTC
