### ISSUE TITLE
02_add_event_data migration error on MariaDB 10.3

### ISSUE THREAD

**Issue by yibudak** [umami-software/umami#1426] opened 2022-08-13 18:34 UTC
Hello,

"RENAME INDEX" syntax is not supported by MariaDB 10.3 (which is the default version on Ubuntu 20.04). `yarn update-db` command fails.
~~~~
Applying migration `01_init`
Applying migration `02_add_event_data`
Error: P3018

A migration failed to apply. New migrations cannot be applied before the error is recovered from. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve

Migration name: 02_add_event_data

Database error code: 1064

Database error:
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'INDEX `session_uuid` TO `session_session_uuid_key`;
ALTER TABLE `session` DR...' at line 2

Please check the query number 16 from the migration file.


error Command failed with exit code 1.

~~~~

**Comment by briancao** [comment] 2022-08-30 18:02
I ran the migraiton against MariaDB manually, and 01/02 files deploy just fine on it.  I tested our custom renaming index function as well, successfully.  

We did perform another release of 1.37.0 without incrementing the release.  Please get the latest version and try again.

More information on troubleshooting can be found here.

https://github.com/umami-software/umami/discussions/1434

**Comment by Maxime-J** [comment] 2022-09-03 17:09
Hello @briancao , I can confirm that issue on older MariaDB versions
RENAME INDEX support was added in 10.5.2 (https://mariadb.com/kb/en/alter-table/#rename-indexkey)

I had to drop the indexes and recreate them.

By the way, that issue left aside, I'm surprised Prisma managed to handle the procedure, because running that 02 migration without Prisma requires a change of DELIMITER, like that:
```
DELIMITER ;;
CREATE PROCEDURE ...........
[...]
END;;
DELIMITER ;
```
It seems you helped a few Prisma users https://github.com/prisma/prisma/issues/12912 with that migration.
:)

**Comment by briancao** [comment] 2022-09-06 05:57
Thank you for all the details!  For whatever reason, I had no issues running the migrations in full against MariaDB, despite no DELIMITER.

Closing this.  Please use 10.5.2 or higher when using MariaDB.

**Closed by briancao** 2022-09-06 05:57 UTC
