### ISSUE TITLE
Firefox Autofill Issue on Login Screen

### ISSUE THREAD

**Issue by ranghaus** [umami-software/umami#2959] opened 2024-09-13 10:50 UTC
### Describe the Bug

When accessing the login screen on Firefox, the browser autofills the email and password fields with saved credentials. However, Umami does not recognize these fields as filled, resulting in a validation error. This forces users to manually retype the login information, even though it has been autofilled correctly.

![firefox_RMwXH5jmiL](https://github.com/user-attachments/assets/d1c7adfa-49ac-4b95-a5f5-efd4f41b582d)

### Database

Umami Cloud

**Comment by franciscao633** [comment] 2024-09-18 18:36
Duplicate of #2449, but yea we definitely need to address it since its been a long known bug.

**Closed by franciscao633** 2024-09-18 18:36 UTC
