### ISSUE TITLE
Wrong URL reported with SvelteKit client-side navigation

### ISSUE THREAD

**Issue by notramo** [umami-software/umami#2637] opened 2024-04-02 14:59 UTC
### Describe the Bug

The full URL is reported when navigating using SvelteKit client-side navigation (clicking a link on the hydrated page).
The correct URL is reported when reloading page, even if the tracker script is inserted during hydration (SSR page does not include it).
E.g. the analytics page shows `https://example.com/contact/` instead of `/contact/` for pages that are navigated client-side.

**This causes incorrect statistics**, as one page can have 2 URLs (relative with direct navigation and absolute with client-side navigation) which have separate view counting.

### Database

Umami Cloud

### Which Umami version are you using? (if relevant)

Umami Cloud

### Which browser are you using? (if relevant)

Firefox

### How are you deploying your application? (if relevant)

Umami Cloud

**Comment by eumarcelo** [comment] 2024-04-06 15:18
Same issue here, any luck solving it?

**Comment by madmax** [comment] 2024-04-07 13:02
Me too :(

**Comment by CediGasser** [comment] 2024-04-15 08:54
Same issue here using self hosted umami v2.11.0. Although, is showing only the path really the intended behavior? With two domains I could not differentiate between them anymore.

**Comment by notramo** [comment] 2024-04-15 12:46
The two domains should have different site IDs probably.

**Comment by mikecao** [comment] 2024-04-16 23:47
Should be fixed by this PR, https://github.com/umami-software/umami/pull/2679. We will release a hotfix.

**Comment by mikecao** [comment] 2024-04-17 06:39
Fixed in v2.11.2.

**Closed by mikecao** 2024-04-17 06:39 UTC
Labels: bug, fixed in dev

**Comment by mikecao** [comment] 2024-12-18 00:31
@acerasoni You would have to run a script to update your data.

**Comment by madmax** [comment] 2024-12-19 01:14
@mikecao What script should be run?

**Comment by mikecao** [comment] 2024-12-19 22:22
@madmax You would have to come up with it. You can probably do it in pure SQL
